//! Biquad filter implementation using kama-core-dsp
//!
//! This module provides a Processor wrapper around the `Biquad` filter from `kama-core-dsp`
//! for use in audio graphs.

use kama_core::{ProcessError, ProcessResult, DEFAULT_BLOCK_SIZE};
use kama_core::traits::{Processor, ParamValue, ParameterId};
use kama_core_dsp::filters::{Biquad, FilterParams, FilterType};
use kama_core_dsp::algorithm::{Algorithm, ParameterizedAlgorithm};
use kama_core::macros::processor_node;

/// A Processor wrapper for the Biquad filter.
///
/// This struct is generated by the `processor_node!` macro, but also provides
/// additional methods for parameter manipulation and algorithm access.
processor_node! {
    /// Biquad processor with configurable filter type and parameters.
    pub struct BiquadProcessor {
        params: {
            /// Cutoff frequency (Hz)
            cutoff: f32 = 1000.0,
            /// Q factor
            q: f32 = 0.707,
            /// Gain in dB (for peak/shelving filters)
            gain_db: f32 = 0.0,
        },
        control_inputs: {},
        state: {
            /// Inner biquad algorithm
            algorithm: Biquad<f32> = Biquad::new(FilterParams {
                filter_type: FilterType::LowPass,
                cutoff: 1000.0,
                q: 0.707,
                gain_db: 0.0,
            }),
            /// Current filter type (not exposed as automatable parameter)
            filter_type: FilterType = FilterType::LowPass,
        },
        inputs: 1,
        outputs: 1,
        process: |this, _channel, input, output, _control| {
            this.algorithm.process_block(&input[..], &mut output[..]);
        },
        after_param_change: |this, param, _value| {
            match param {
                "cutoff" | "q" | "gain_db" => {
                    this.update_algorithm();
                }
                _ => {}
            }
        }
    }
}

impl BiquadProcessor {
    /// Creates a new Biquad processor with the given filter parameters.
    pub fn from_params(params: FilterParams) -> Self {
        let mut instance = Self::new_with_defaults();
        instance.cutoff = params.cutoff;
        instance.q = params.q;
        instance.gain_db = params.gain_db;
        instance.filter_type = params.filter_type;
        instance.update_algorithm();
        instance
    }

    /// Creates a new Biquad processor with individual parameters (backward compatibility).
    pub fn new_with_params(
        filter_type: FilterType,
        cutoff: f32,
        q: f32,
        gain_db: f32,
    ) -> Self {
        let params = FilterParams {
            filter_type,
            cutoff,
            q,
            gain_db,
        };
        Self::from_params(params)
    }

    /// Helper constructor that returns an instance with default values.
    /// Used internally by the macro expansion.
    fn new_with_defaults() -> Self {
        Self::from_params(FilterParams {
            filter_type: FilterType::LowPass,
            cutoff: 1000.0,
            q: 0.707,
            gain_db: 0.0,
        })
    }

    /// Returns the current cutoff frequency (Hz).
    pub fn cutoff(&self) -> f32 {
        self.cutoff
    }

    /// Sets the cutoff frequency (Hz) and updates coefficients.
    pub fn set_cutoff(&mut self, cutoff: f32) {
        self.cutoff = cutoff.max(20.0).min(20000.0);
        self.update_algorithm();
    }

    /// Returns the current Q factor.
    pub fn q(&self) -> f32 {
        self.q
    }

    /// Sets the Q factor and updates coefficients.
    pub fn set_q(&mut self, q: f32) {
        self.q = q.max(0.1).min(20.0);
        self.update_algorithm();
    }

    /// Returns the current gain in dB (for peak/shelving filters).
    pub fn gain_db(&self) -> f32 {
        self.gain_db
    }

    /// Sets the gain in dB and updates coefficients.
    pub fn set_gain_db(&mut self, gain_db: f32) {
        self.gain_db = gain_db.max(-24.0).min(24.0);
        self.update_algorithm();
    }

    /// Returns the current filter type.
    pub fn filter_type(&self) -> FilterType {
        self.filter_type
    }

    /// Sets the filter type and updates coefficients.
    pub fn set_filter_type(&mut self, filter_type: FilterType) {
        self.filter_type = filter_type;
        self.update_algorithm();
    }

    /// Returns a reference to the inner algorithm.
    pub fn algorithm(&self) -> &Biquad<f32> {
        &self.algorithm
    }

    /// Returns a mutable reference to the inner algorithm.
    pub fn algorithm_mut(&mut self) -> &mut Biquad<f32> {
        &mut self.algorithm
    }

    /// Updates the inner algorithm with current parameters.
    fn update_algorithm(&mut self) {
        let params = FilterParams {
            filter_type: self.filter_type,
            cutoff: self.cutoff,
            q: self.q,
            gain_db: self.gain_db,
        };
        self.algorithm.set_params(params);
        // Re‑initialize if sample rate has changed (should be done via `init`)
        if self.sample_rate > 0.0 {
            self.algorithm.init(self.sample_rate);
        }
    }


}

/// Re-export of the generic Biquad filter from kama-core-dsp for advanced use.
pub use kama_core_dsp::filters::Biquad as BiquadFilterGeneric;

/// Type alias for backward compatibility (f32 specialization).
/// NOTE: This type does NOT implement Processor; use `BiquadProcessor` for graph integration.
pub type BiquadFilter = BiquadFilterGeneric<f32>;

/// Extension trait providing convenience methods for Biquad filter.
pub trait BiquadExt<T> {
    /// Get cutoff frequency (Hz)
    fn cutoff(&self) -> f32;
    /// Set cutoff frequency (Hz)
    fn set_cutoff(&mut self, cutoff: f32);
    /// Get Q factor
    fn q(&self) -> f32;
    /// Set Q factor
    fn set_q(&mut self, q: f32);
    /// Get gain in dB (for peak/shelving filters)
    fn gain_db(&self) -> f32;
    /// Set gain in dB
    fn set_gain_db(&mut self, gain_db: f32);
    /// Get filter type
    fn filter_type(&self) -> FilterType;
    /// Set filter type
    fn set_filter_type(&mut self, filter_type: FilterType);
}

impl<T: kama_core::AudioNum> BiquadExt<T> for Biquad<T>
where
    Biquad<T>: ParameterizedAlgorithm<T, Params = FilterParams>,
{
    fn cutoff(&self) -> f32 {
        self.params().cutoff
    }

    fn set_cutoff(&mut self, cutoff: f32) {
        let mut params = self.params().clone();
        params.cutoff = cutoff.max(20.0).min(20000.0);
        self.set_params(params);
    }

    fn q(&self) -> f32 {
        self.params().q
    }

    fn set_q(&mut self, q: f32) {
        let mut params = self.params().clone();
        params.q = q.max(0.1).min(20.0);
        self.set_params(params);
    }

    fn gain_db(&self) -> f32 {
        self.params().gain_db
    }

    fn set_gain_db(&mut self, gain_db: f32) {
        let mut params = self.params().clone();
        params.gain_db = gain_db.max(-24.0).min(24.0);
        self.set_params(params);
    }

    fn filter_type(&self) -> FilterType {
        self.params().filter_type
    }

    fn set_filter_type(&mut self, filter_type: FilterType) {
        let mut params = self.params().clone();
        params.filter_type = filter_type;
        self.set_params(params);
    }
}

// Helper functions for converting FilterType to/from string.
fn filter_type_to_string(ft: FilterType) -> String {
    match ft {
        FilterType::LowPass => "LowPass".to_string(),
        FilterType::HighPass => "HighPass".to_string(),
        FilterType::BandPass => "BandPass".to_string(),
        FilterType::Notch => "Notch".to_string(),
        FilterType::Peak => "Peak".to_string(),
        FilterType::LowShelf => "LowShelf".to_string(),
        FilterType::HighShelf => "HighShelf".to_string(),
        FilterType::AllPass => "AllPass".to_string(),
    }
}

fn string_to_filter_type(s: &str) -> Option<FilterType> {
    match s {
        "LowPass" => Some(FilterType::LowPass),
        "HighPass" => Some(FilterType::HighPass),
        "BandPass" => Some(FilterType::BandPass),
        "Notch" => Some(FilterType::Notch),
        "Peak" => Some(FilterType::Peak),
        "LowShelf" => Some(FilterType::LowShelf),
        "HighShelf" => Some(FilterType::HighShelf),
        "AllPass" => Some(FilterType::AllPass),
        _ => None,
    }
}

/// Backward‑compatibility wrapper for `BiquadFilter::new` with four arguments.
pub fn new(filter_type: FilterType, cutoff: f32, q: f32, gain_db: f32) -> BiquadFilter {
    BiquadFilter::new(FilterParams {
        filter_type,
        cutoff,
        q,
        gain_db,
    })
}
